# Generated by Django 6.0.4 on 2026-04-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discuss", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "帖子", "verbose_name_plural": "帖子"},
        ),
    ]
